name: Deploy to CDN

on:
  push:
    branches:
      - master
      - cdnv2

jobs:
  build:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::762706324393:role/github-actions-cdn-geolonia-deploy

      - name: Deploy to S3
        run: |
          aws s3 sync ./public s3://gl-cdn-ap-northeast-1 --delete --cache-control public,max-age=86400 --exclude "_headers"
