name: comment_on_pr

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci

      - id: create_comment_diff
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          COMMENT=$(node bin/compare-styles.mjs $BASE_BRANCH $BRANCH_NAME)
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post comment
        uses: actions/github-script@v8
        if: github.event_name == 'pull_request' && steps.create_comment_diff.outputs.comment
        env:
          POSTING_COMMENT_BODY: ${{ steps.create_comment_diff.outputs.comment }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            await github.rest.issues.createComment({ issue_number, owner, repo, body: process.env.POSTING_COMMENT_BODY });
